---
layout: page
title: 데이터 과학자가 바라본 20대 총선
subtitle: 인구 통계(demography)
output:
  html_document: 
    keep_md: yes
  pdf_document:
    latex_engine: xelatex
mainfont: NanumGothic
---

``` {r setOptions, message=FALSE, include=FALSE}
source("tools/chunk-options.R")
library(googleVis)
op <- options(gvis.plot.tag='chart')
#knitr::opts_chunk$set(cache=TRUE)
```


## 선거구

선거구 획정 관련 이슈

## 제20대 선거구 

제20대 선거구 데이터는 팀포퐁 [GitHub](https://github.com/southkorea/southkorea-maps)에서 가져온다. GeoJSON과 
Topo JSON 형식을 모두 지원한다.
`ogrListLayers` 함수를 통해서 사용할 `layer=`를 확인한다.

``` {r korea_precinct, results='asis', tidy=FALSE}
library(rgeos)
library(rgdal) # gdal > 1.11.0
library(ggplot2)

ogrListLayers("../southkorea-maps/popong/precinct/assembly-precinct-20-geo.json")
# precincts
 
ogrInfo("../southkorea-maps/popong/precinct/assembly-precinct-20-geo.json", "precincts")

map.20 <-  readOGR(dsn="../southkorea-maps/popong/precinct/assembly-precinct-20-geo.json", layer="precincts")

map.19 <-  readOGR(dsn="../southkorea-maps/popong/precinct/assembly-precinct-19-geo.json", layer="precincts")

par(mfrow = c(1, 2))  # 1 rows and 2 columns
plot(map.19)
plot(map.20)
```

출처: [Overcoming D3 Cartographic Envy With R + ggplot](https://rud.is/b/2014/09/26/overcoming-d3-cartographic-envy-with-r-ggplot/)

