---
layout: page
title: 데이터 과학자와 함께 하는 제19대 대통령 선거
subtitle: 페이스북 페이지 팬수 추세(문,안)
output:
  html_document: 
    keep_md: yes
  pdf_document:
    latex_engine: xelatex
mainfont: NanumGothic
---

```{r setOptions, message=FALSE, include=FALSE}
source("tools/chunk-options.R")
```


## 페이스북 페이지 팬수 추세

민주당 문재인 후보와 국민의당 안철수 후보가 양강 체계를 구축하고 치열한 각축전을 벌이고 있다.
페이스북 팬수 추세를 시각화 한다.


### 페이스북 페이지 팬수 비교 

``` {r facebook-page-moon-ahn, echo=FALSE, warn=FALSE, message=FALSE}
# 0. 참고문헌 ---------------------------------------------------------------------
library(Rfacebook)
library(RCurl)
library(tidyverse)
library(lubridate)
library(ggplot2)
library(stringr)
library(DT)
library(gridExtra)
library(ggthemes)
library(extrafont)
loadfonts()

fb_keys <- "EAACEdEose0cBAEGzXmAQQ81DjUiGSMhTx6zGmZAnTfsLup00ZCX2x1rTNR2lVpyk7LSFazJPZCkTzm5dc1hEpVQya6uZCf6GFIMzxDkxjimg2X2fva9ARnkLAVNYFwQ6ya7BgsGZAATlyjdbkuGoilZAHdoHQxUic2ztWluxngbyfzq8MGLU1U"

# 1. 데이터 불러오기 ---------------------------------------------------------------------

## 1.1. 페북 데이터 데이터---------------------------------

get_fb_likes <- function(fb_pages, sdate, edate, fb_keys){
  url         <- paste0("https://graph.facebook.com/v2.8/", fb_pages, "/insights/page_fans_country/lifetime?&since=", sdate, "&until=", edate, "&access_token=", fb_keys)
  url_json    <- getURL(url)
  url_list    <- fromJSON(url_json)
  url_dat_likes  <- lapply(url_list$data[[1]]$values, function(x) {x$value})
  library(gtools)
  url_dat_df <- do.call(smartbind, url_dat_likes)
  url_dat_df[is.na(url_dat_df)] <- 0
  url_date <- lapply(url_list$data[[1]]$values, function(x) {x$end_time})
  url_date_df <- do.call(rbind, url_date)
  
  url_df <- cbind(url_date_df, url_dat_df)
  url_df <- url_df %>%
    mutate(url_date_df = ymd(str_sub(url_date_df, 1, 10))) %>% 
    dplyr::rename(fdate=url_date_df)
  return(url_df)
}

# 2. 데이터 가져오기 ---------------------------------------------------------------

## 2.1. 안철수
ahn_fan_1703 <- get_fb_likes("ahncs111", "2017-01-01", "2017-03-30", fb_keys)
ahn_fan_1704 <- get_fb_likes("ahncs111", "2017-03-30", "2017-04-20", fb_keys)

ahn_fan <- bind_rows(ahn_fan_1703, ahn_fan_1704)

ahn_fan_lng <- ahn_fan %>% 
  gather(`iso-a2`, fans, -fdate) %>% 
  mutate(fans = ifelse(is.na(fans), 0, fans))
  
ahn_fan_lng <- ahn_fan_lng %>% 
  group_by(fdate) %>% 
  dplyr::summarise(ahn_fans = sum(fans))


## 2.2. 문재인
moon_fan_1703 <- get_fb_likes("moonbyun1", "2017-01-01", "2017-03-30", fb_keys)
moon_fan_1704 <- get_fb_likes("moonbyun1", "2017-03-30", "2017-04-20", fb_keys)

moon_fan <- bind_rows(moon_fan_1703, moon_fan_1704)

moon_fan_lng <- moon_fan %>% 
  gather(`iso-a2`, fans, -fdate) %>% 
  mutate(fans = ifelse(is.na(fans), 0, fans))

moon_fan_lng <- moon_fan_lng %>% 
  group_by(fdate) %>% 
  dplyr::summarise(moon_fans = sum(fans))

## 2.3. 후보 병합
fb_fans_df <- left_join(ahn_fan_lng, moon_fan_lng, by="fdate")

fb_fans_df <- fb_fans_df %>% 
  mutate(ratio = moon_fans / ahn_fans)

# 3. 데이터 시각화 ---------------------------------------------------------------

DT::datatable(fb_fans_df) %>% 
  DT::formatCurrency(c(2,3), '', mark=",", digits=0) %>% 
  DT::formatCurrency(c(4), '', mark=",", digits=2)
```

### 페이스북 페이지 팬수 비교 

``` {r facebook-page-moon-ahn-viz, echo=FALSE}
# 3.1. 문재인 vs. 안철수 별도 그래프
ahn_p <- fb_fans_df %>% 
  ggplot(aes(x= fdate, y=ahn_fans)) +
  geom_line(colour="green") +
  geom_point(size=0.3, colour="green") +
  scale_x_date(date_labels = "%m-%d") +
  scale_y_continuous(labels=scales::comma) +
  theme_minimal(base_family="NanumGothic") +
  labs(x="",y="",title="안철수 페이스북 팬 추세",
       caption="\n 자료: 페북 페이지(ahncs111)") +
  theme(legend.position="none")

moon_p <- fb_fans_df %>% 
  ggplot(aes(x= fdate, y=moon_fans)) +
  geom_line(colour="skyblue") +
  geom_point(size=0.3, colour="skyblue") +
  scale_x_date(date_labels = "%m-%d") +
  scale_y_continuous(labels=scales::comma) +
  theme_minimal(base_family="NanumGothic") +
  labs(x="",y="",title="문재인 페이스북 팬 추세",
       caption="\n 자료: 페북 페이지(moonbyun1)") +
  theme(legend.position="none")

grid.arrange(ahn_p, moon_p, nrow=1)

# 3.2. 문재인 vs. 안철수 한장
fb_fans_df %>% dplyr::select(-ratio) %>% 
  gather(candidate, fans, -fdate) %>% 
  ggplot(aes(x= fdate, y=fans, color=candidate)) +
  geom_line() +
  geom_point(size=0.3) +
  scale_x_date(date_labels = "%m-%d") +
  scale_y_continuous(labels=scales::comma) +
  theme_minimal(base_family="NanumGothic") +
  labs(x="",y="",title="페이스북 팬 추세",
       caption="\n 자료출처: Facebook for Developers, 그래프 API 탐색기") +
  theme(legend.position="top") 
```